(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let state={tablets:[],licenses:[],history:[],selectedApps:new Set(),dashboardUrl:location.href};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=value=>'PHP '+Number(value||0).toFixed(2);
const mode=value=>({0:'CENTRALIZED SMART CHARGING',1:'CENTRALIZED MODE',3:'STANDALONE SMART CHARGING',4:'DIRECT USB CHARGER ONLY'}[value]||String(value||'UNKNOWN'));
const ago=value=>{if(!value)return'NEVER';const seconds=Math.max(0,(Date.now()-new Date(value.replace(' ','T')+'Z'))/1000);if(seconds<60)return Math.floor(seconds)+'s ago';if(seconds<3600)return Math.floor(seconds/60)+'m ago';if(seconds<86400)return Math.floor(seconds/3600)+'h ago';return Math.floor(seconds/86400)+'d ago';};
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.style.borderColor=error?'#ff4d59':'#38bdf8';el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),4000);}
function busy(button,work){const old=button.textContent;button.disabled=true;button.textContent='PLEASE WAIT…';return Promise.resolve().then(work).catch(e=>toast(e.message||String(e),true)).finally(()=>{button.disabled=false;button.textContent=old;});}
function showLogin(message='',error=false){$('#app').classList.add('hidden');$('#login').classList.remove('hidden');if(message){$('#login-message').textContent=message;$('#login-message').classList.toggle('error',error);}}
function showApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');}
function target(){const location=$('#admin-location').value,tabletId=Number($('#admin-tablet').value||0);return tabletId?{tabletId}:location&&location!=='ALL LOCATIONS'?{location}:{};}
function sourceTablet(){return state.tablets.find(t=>String(t.id)===$('#source-tablet').value);}
function page(name){$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$$('.page').forEach(x=>x.classList.toggle('active',x.id===name+'-page'));const labels={dashboard:['Monitoring Dashboard','All registered locations and tablets'],admin:['Dashboard Admin Settings','Remote fleet settings and Play Store deployment'],licenses:['Manage Licenses','Availability, ownership, history and transfers']};$('#page-title').textContent=labels[name][0];$('#page-subtitle').textContent=labels[name][1];if(name==='licenses')loadLicenses();}
function stat(label,value,color=''){return`<div class="stat"><b${color?` style="color:${color}"`:''}>${esc(value)}</b><small>${esc(label)}</small></div>`;}
function tabletCard(t){const preview=t.preview?`<img src="${esc(t.preview)}" alt="${esc(t.device)} preview">`:'REMOTE SCREEN PREVIEW<br><small>Waiting for the next secure snapshot</small>';return`<article class="tablet-card" data-tablet="${t.id}"><div class="preview" data-preview="${t.id}">${preview}</div><div class="tablet-body"><div class="tablet-head"><h3>${esc(t.device)}</h3><span class="status ${t.online?'online':'offline'}">${t.online?'ONLINE':'OFFLINE'}</span></div><div class="tablet-meta">${esc(mode(t.mode))}<br>Battery: ${Number(t.battery||0)}% · Last seen: ${esc(ago(t.lastSeen))}<br>Preview: ${esc(ago(t.previewAt))} · Launcher: ${esc(t.launcherVersion||'UNKNOWN')}</div><div class="sales"><div class="sale"><small>TODAY</small>${money(t.sales?.today)}</div><div class="sale"><small>THIS WEEK</small>${money(t.sales?.week)}</div><div class="sale"><small>THIS MONTH</small>${money(t.sales?.month)}</div><div class="sale"><small>ALL-TIME</small>${money(t.sales?.allTime)}</div></div><div class="tablet-actions"><button data-remote="${t.id}">REMOTE CONTROL</button><button data-settings="${t.id}" class="secondary">ADMIN SETTINGS</button></div></div></article>`;}
function renderDashboard(data){state.tablets=data.tablets||[];const online=state.tablets.filter(x=>x.online).length,locations=[...new Set(state.tablets.map(x=>x.location||'UNASSIGNED'))];$('#summary-cards').innerHTML=stat('ONLINE TABLETS',online,'#12d977')+stat('REGISTERED TABLETS',state.tablets.length)+stat('LOCATIONS',locations.length,'#38bdf8')+stat('ALL-TIME SALES',money(data.sales?.allTime),'#ffc13d');$('#locations').innerHTML=locations.map(location=>{const tablets=state.tablets.filter(x=>(x.location||'UNASSIGNED')===location);return`<section><div class="location-title"><h2>${esc(location)}</h2><span>${tablets.length} TABLET${tablets.length===1?'':'S'}</span></div><div class="tablet-grid">${tablets.map(tabletCard).join('')}</div></section>`;}).join('')||'<div class="panel">No registered tablets yet.</div>';fillTargets();bindTabletButtons();}
function fillTargets(){const locations=[...new Set(state.tablets.map(x=>x.location||'UNASSIGNED'))];$('#admin-location').innerHTML='<option>ALL LOCATIONS</option>'+locations.map(x=>`<option>${esc(x)}</option>`).join('');fillTablets();$('#source-tablet').innerHTML=state.tablets.map(x=>`<option value="${x.id}">${esc((x.location||'UNASSIGNED')+' / '+x.device)}</option>`).join('');}
function fillTablets(){const location=$('#admin-location').value;const tablets=state.tablets.filter(x=>location==='ALL LOCATIONS'||(x.location||'UNASSIGNED')===location);$('#admin-tablet').innerHTML='<option value="">ALL TABLETS IN TARGET</option>'+tablets.map(x=>`<option value="${x.id}">${esc(x.device)}</option>`).join('');}
async function refresh(){const data=await CoinTabApi.summary();renderDashboard(data);$('#server-pill').className=$('#online-pill').className='pill good';}
function modal(html){$('#modal-content').innerHTML=html;$('#modal').classList.remove('hidden');}
function closeModal(){$('#modal').classList.add('hidden');$('#modal-content').innerHTML='';}
function bindTabletButtons(){$$('[data-preview]').forEach(el=>el.onclick=()=>{const t=state.tablets.find(x=>x.id==el.dataset.preview);if(t?.preview)modal(`<h2>${esc(t.device)} — SCREEN PREVIEW</h2><img src="${esc(t.preview)}" style="width:100%;max-height:75vh;object-fit:contain;background:#000">`);});$$('[data-remote]').forEach(el=>el.onclick=()=>remoteModal(Number(el.dataset.remote)));$$('[data-settings]').forEach(el=>el.onclick=()=>settingsModal(Number(el.dataset.settings)));}
function remoteModal(id){const t=state.tablets.find(x=>x.id===id);modal(`<h2>${esc(t.device)} — REMOTE CONTROL</h2><p>Commands are queued and applied when the licensed tablet is online. Reboot and power lock require Device Owner.</p><div class="remote-grid"><button data-cmd="SCREEN_ON">TURN SCREEN ON</button><button data-cmd="BACK">BACK</button><button data-cmd="HOME">HOME</button><button data-cmd="RECENTS">RECENTS</button><button data-cmd="OPEN_WIFI">OPEN WI-FI</button><button data-cmd="POWER" class="danger">POWER / LOCK</button><button data-cmd="REBOOT" class="danger">REBOOT DEVICE</button></div><textarea id="remote-message" class="remote-message" placeholder="Message to display on the tablet"></textarea><button id="send-message">SEND MESSAGE</button>`);$$('[data-cmd]').forEach(button=>button.onclick=()=>busy(button,async()=>{await CoinTabApi.command(button.dataset.cmd,{tabletId:id},{});toast(button.dataset.cmd+' queued');closeModal();}));$('#send-message').onclick=()=>busy($('#send-message'),async()=>{const message=$('#remote-message').value.trim();if(!message)throw new Error('Enter a message first.');await CoinTabApi.command('MESSAGE',{tabletId:id},{message});toast('Message queued');closeModal();});}
function settingsModal(id){const t=state.tablets.find(x=>x.id===id),s=t.settings||{};modal(`<h2>${esc(t.device)} — TABLET ADMIN SETTINGS</h2><div class="form-grid"><label>Device Name<input id="m-device" value="${esc(t.device)}"></label><label>Location<input id="m-location" value="${esc(t.location||'')}"></label><label>Cleanup Delay (minutes)<input id="m-cleanup" type="number" min="0" max="1440" value="${Number(s.cleanup??10)}"></label><label>Preview Refresh (seconds)<input id="m-preview" type="number" min="5" max="300" value="${Number(s.screenMonitorRemoteInterval??15)}"></label><label class="check"><input id="m-widget" type="checkbox" ${s.timeWidget!==false?'checked':''}> Time Left Widget</label><label class="check"><input id="m-monitor" type="checkbox" ${s.screenMonitoringEnabled!==false?'checked':''}> Remote Screen Monitoring</label><label>New Administrator PIN (optional)<input id="m-pin" inputmode="numeric" maxlength="8" placeholder="Leave blank to keep current PIN"></label></div><div class="button-row"><button id="m-save">SAVE TO TABLET</button><button id="m-reset" class="danger">RESET TABLET SALES</button><button id="m-update">UPDATE LAUNCHER</button><button id="m-cancel" class="secondary">CANCEL</button></div>`);$('#m-cancel').onclick=closeModal;$('#m-save').onclick=()=>busy($('#m-save'),async()=>{const settings={deviceName:$('#m-device').value.trim(),locationName:$('#m-location').value.trim(),cleanup:Number($('#m-cleanup').value),screenMonitorRemoteInterval:Number($('#m-preview').value),timeWidget:$('#m-widget').checked,screenMonitoringEnabled:$('#m-monitor').checked};const pin=$('#m-pin').value.trim();if(pin)settings.newAdminPin=pin;await CoinTabApi.command('APPLY_SETTINGS',{tabletId:id},{settings});toast('Tablet settings queued');closeModal();});$('#m-reset').onclick=()=>busy($('#m-reset'),async()=>{await CoinTabApi.resetSales(id);toast('Tablet sales reset queued');closeModal();});$('#m-update').onclick=()=>busy($('#m-update'),async()=>{await CoinTabApi.command('UPDATE_LAUNCHER',{tabletId:id},{});toast('Launcher update queued');closeModal();});}
async function loadLicenses(){const [licenses,history]=await Promise.all([CoinTabApi.licenses(),CoinTabApi.licenseHistory()]);state.licenses=licenses.licenses||[];state.history=history.history||[];renderLicenses();}
function renderLicenses(){const query=$('#license-search').value.trim().toLowerCase();const rows=state.licenses.filter(x=>JSON.stringify(x).toLowerCase().includes(query));$('#license-list').innerHTML=rows.map(x=>`<div class="license"><div><b>${esc(x.licenseKey||x.key)}</b><small>${esc(x.email)} · ${esc(x.type)} · ${esc(x.device||'NOT ASSIGNED')} · ${esc(x.location||'')}</small></div><span class="status ${x.status==='USED'?'online':x.status==='AVAILABLE'?'':'offline'}">${esc(x.status)}</span><button data-license-action="${x.status==='REVOKED'?'restore':'revoke'}" data-key="${esc(x.licenseKey||x.key)}" class="secondary">${x.status==='REVOKED'?'RESTORE':'REVOKE'}</button><button data-transfer="${esc(x.licenseKey||x.key)}">TRANSFER</button></div>`).join('')||'<p>No matching licenses.</p>';$('#license-history').innerHTML=state.history.map(x=>`<div class="history-row"><b>${esc(x.event_type)}</b><span>${esc(x.license_key)}</span><small>${esc(x.created_at)}</small></div>`).join('')||'<p>No license history.</p>';$$('[data-license-action]').forEach(button=>button.onclick=()=>busy(button,async()=>{if(button.dataset.licenseAction==='restore')await CoinTabApi.restore(button.dataset.key);else await CoinTabApi.revoke(button.dataset.key);toast('License updated');await loadLicenses();}));$$('[data-transfer]').forEach(button=>button.onclick=()=>{const email=prompt('New owner Gmail');if(!email)return;const seller=confirm('Keep the currently activated tablet and transfer its dashboard/settings to the new owner?\n\nOK = Seller transfer\nCancel = Normal transfer');CoinTabApi.transfer(button.dataset.transfer,email,seller).then(()=>{toast('License transferred');loadLicenses();}).catch(e=>toast(e.message,true));});}
function selectedPackages(){const packages=[...state.selectedApps];const optional=$('#package').value.trim();if(optional&&!packages.includes(optional))packages.push(optional);if(!packages.length)throw new Error('Select or enter at least one package.');return packages;}
function renderSourceApps(){const t=sourceTablet(),apps=t?.apps||[];state.selectedApps.clear();$('#source-apps').innerHTML=apps.map(a=>`<label class="app-item"><input type="checkbox" data-package="${esc(a.package)}"><img src="${esc(a.icon||'')}" onerror="this.style.display='none'"><span>${esc(a.label||a.package)}<small>${esc(a.package)}</small></span></label>`).join('')||'<p>This tablet has not uploaded its installed-app list yet.</p>';$$('[data-package]').forEach(box=>box.onchange=()=>box.checked?state.selectedApps.add(box.dataset.package):state.selectedApps.delete(box.dataset.package));}
async function initialize(){try{const access=new URLSearchParams(location.search).get('access');if(access&&!CoinTabApi.hasSession())await CoinTabApi.access(access);if(!CoinTabApi.hasSession())return showLogin();showApp();await refresh();}catch(error){CoinTabApi.logout();showLogin(error.message,true);}}
$('#login-form').onsubmit=event=>{event.preventDefault();busy(event.submitter,async()=>{await CoinTabApi.login($('#email').value.trim(),$('#pin').value.trim());showApp();await refresh();});};$('#logout').onclick=()=>{CoinTabApi.logout();showLogin('Signed out successfully.');};$('#refresh').onclick=()=>busy($('#refresh'),refresh);$('#admin-shortcut').onclick=()=>page('admin');$$('[data-page]').forEach(button=>button.onclick=()=>page(button.dataset.page));$('#admin-location').onchange=fillTablets;$('#modal-close').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal();};$('#license-search').oninput=renderLicenses;
$('#reset-sales').onclick=()=>busy($('#reset-sales'),async()=>{const t=target();await CoinTabApi.resetSales(t.tabletId||null,t.location||'');toast('Sales reset queued');await refresh();});
$('#apply-theme').onclick=()=>busy($('#apply-theme'),async()=>{await CoinTabApi.command('APPLY_SETTINGS',target(),{settings:{uiTheme:Number($('#theme').value),categoryMode:$('#categories').checked,dailyThemeRotation:$('#daily-theme').checked}});toast('Appearance settings queued');});
$('#update-launcher').onclick=()=>busy($('#update-launcher'),async()=>{await CoinTabApi.command('UPDATE_LAUNCHER',target(),{});toast('Launcher update queued');});
$('#apply-network').onclick=()=>busy($('#apply-network'),async()=>{await CoinTabApi.command('APPLY_SETTINGS',target(),{settings:{blockAdultSites:$('#adult').checked,blockAdDomains:$('#ads').checked,vpnControlsEnabled:$('#vpn').checked,protectedGoogleAccount:$('#protected-email').value.trim()}});toast('Network settings queued');});
$('#load-apps').onclick=renderSourceApps;$('#select-all').onclick=()=>{$$('[data-package]').forEach(box=>{box.checked=true;state.selectedApps.add(box.dataset.package);});};
$('#install-apps').onclick=()=>busy($('#install-apps'),async()=>{await CoinTabApi.command('INSTALL_APPS',target(),{packages:selectedPackages()});toast('App installation queued');});
$('#update-apps').onclick=()=>busy($('#update-apps'),async()=>{await CoinTabApi.command('UPDATE_APPS',target(),{packages:selectedPackages()});toast('App updates queued');});
$('#uninstall-apps').onclick=()=>busy($('#uninstall-apps'),async()=>{await CoinTabApi.command('UNINSTALL_APPS',target(),{packages:selectedPackages()});toast('App uninstall queued');});
$('#stop-apps').onclick=()=>busy($('#stop-apps'),async()=>{await CoinTabApi.command('STOP_APP_MAINTENANCE',target(),{});toast('Stop command queued');});
$('#email-link').onclick=()=>busy($('#email-link'),async()=>{const data=await CoinTabApi.dashboardLink(true);state.dashboardUrl=data.dashboardUrl;toast('Dashboard link email requested');});
$('#copy-link').onclick=()=>busy($('#copy-link'),async()=>{const data=await CoinTabApi.dashboardLink(false);state.dashboardUrl=data.dashboardUrl;await navigator.clipboard.writeText(data.dashboardUrl);toast('Permanent dashboard link copied');});
setInterval(()=>{if(CoinTabApi.hasSession()&&!document.hidden)refresh().catch(()=>{$('#server-pill').className=$('#online-pill').className='pill bad';});},30000);initialize();
})();
